@baseUrl = http://localhost:5353/api/v1

@authUrl = {{baseUrl}}/auth

@userUrl = {{baseUrl}}/users

@cartUrl = {{baseUrl}}/cart

@productUrl = {{baseUrl}}/public/products

@orderUrl = {{baseUrl}}/orders

@paymentUrl = {{baseUrl}}/payments

# --- AUTHENTICATION ---

### signin
POST {{authUrl}}/public/signin HTTP/1.1
Content-Type: application/json

{
    "email": "fatihb469@gmail.com"
}

### verify-login-otp
POST {{authUrl}}/public/signin-verify HTTP/1.1
Content-Type: application/json

{
  "email": "fatihb469@gmail.com",
  "code": "864683"
}

### refresh-token
POST {{authUrl}}/public/refresh-token HTTP/1.1

# --- USERS ---

### me
GET {{userUrl}}/me HTTP/1.1

### addresses
GET {{userUrl}}/addresses HTTP/1.1

# --- PRODUCTS ---

### get-products
GET {{productUrl}} HTTP/1.1

### list-products (search-query)
GET {{productUrl}}?query=iphone HTTP/1.1

@slug = urun-2-2c60d725

### get-product-by-slug
GET {{productUrl}}/slug/{{slug}} HTTP/1.1

# --- CART ---

### add-to-cart
POST {{cartUrl}}/items HTTP/1.1
Content-Type: application/json

{
  "variantId":"1fdf8b19-e637-449f-a97e-a5c2a7645024",
  "quantity": 1
}

### get-cart
GET {{cartUrl}} HTTP/1.1

@cartItemId = a05f6c8b-0fd5-4439-a40c-15b39727a097

### update-cart-item
PATCH {{cartUrl}}/items/{{cartItemId}} HTTP/1.1
Content-Type: application/json

{
  "quantity": 31
}

### remove-cart-item
DELETE {{cartUrl}}/items/{{cartItemId}} HTTP/1.1

# --- ORDER ---

### checkout-preview
POST {{orderUrl}}/checkout/preview HTTP/1.1
Content-Type: application/json

{
  "items": ["eb760d6b-a80b-46d0-b758-d62e87b5a53a", "1fdf8b19-e637-449f-a97e-a5c2a7645024"]
}

### checkout
POST {{orderUrl}}/checkout HTTP/1.1
Content-Type: application/json

{
  "shippingAddressId" : "9f050d82-c9ac-4a44-964d-288792a9b350",
  "billingAddressId" : "9f050d82-c9ac-4a44-964d-288792a9b350",
  "items": ["1fdf8b19-e637-449f-a97e-a5c2a7645024"]
}

### get-orders
GET {{orderUrl}} HTTP/1.1

@orderId = eea046a4-9f36-438b-b39f-07a3e91cd943

### get-order-by-id
GET {{orderUrl}}/{{orderId}} HTTP/1.1

# --- PAYMENT ---

### create-payment-intent
POST {{paymentUrl}} HTTP/1.1
Content-Type: application/json

{
  "orderId": "085614bc-4549-4582-9213-3355500d564d",
  "callbackUrl": "http://localhost:3000/payment-callback"
}

### get-payment-details
GET {{paymentUrl}}/de220f3c-defd-445e-9311-230083d8768d HTTP/1.1