server.port=5353

# --- POSTGRESQL (Local) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# --- REDIS (Local) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- JWT CONFIGURATION ---
selahattin.dev.jwt.access-secret-key=f2a606644100eeedd65189534b7e0d812c053525a5619fa6b58ff431a85232c7
selahattin.dev.jwt.refresh-secret-key=88cc6d801a5e42c300c31cac36c673785ccbe500b6ff22f8cb417a32f6cb7f7a
selahattin.dev.jwt.access-token-expiration-ms=6000000
selahattin.dev.jwt.refresh-token-expiration-ms=604800000

# --- SPRING MAIL (Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=selahattingungor0053@gmail.com
spring.mail.password=qzinfvsrgjykalwx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

# --- CLIENT PROPERTIES ---
selahattin.dev.client.backend-url=http://localhost:5353
selahattin.dev.client.frontend-url=http://localhost:3000
selahattin.dev.client.email-verification-path=/auth/sign-up/verify?id=
selahattin.dev.client.cors-allowed-origins=http://localhost:3000

# ==========================================
# PAYMENT CONFIGURATION (DEV - SANDBOX)
# ==========================================
selahattin.dev.payment.active-provider=IYZICO

# --- STRIPE (Test Keys) ---
selahattin.dev.payment.stripe.api-key=sk_test_dummy_dev_key
selahattin.dev.payment.stripe.publishable-key=pk_test_dummy_dev_key
selahattin.dev.payment.stripe.webhook-secret=whsec_dummy_dev_secret

# --- IYZICO (Sandbox Keys) ---
selahattin.dev.payment.iyzico.api-key=sandbox-4AUxndXI6C4boCoBDweeSmw1rpa1bYAI
selahattin.dev.payment.iyzico.secret-key=sandbox-OvEBexE5WCzX0pBNgc9olPCeedXtHYTz
selahattin.dev.payment.iyzico.base-url=https://sandbox-api.iyzipay.com
selahattin.dev.payment.iyzico.callback-url=${selahattin.dev.client.backend-url}/api/v1/webhooks/payments/iyzico