-- Önce Türkiye'yi ekleyelim (Eğer yoksa)
INSERT INTO countries (id, name)
VALUES (1, 'Türkiye')
ON CONFLICT (id) DO NOTHING;

-- Şehirleri ekleyelim (country_id = 1 olarak belirtiyoruz)
-- Tek bir INSERT bloğu kullanmak veritabanı performansı açısından 81 ayrı insert'ten daha iyidir.
INSERT INTO cities (id, country_id, name)
VALUES (1, 1, 'ADANA'),
       (2, 1, 'ADIYAMAN'),
       (3, 1, 'AFYONKARAHİSAR'),
       (4, 1, 'AĞRI'),
       (5, 1, 'AKSARAY'),
       (6, 1, 'AMASYA'),
       (7, 1, 'ANKARA'),
       (8, 1, 'ANTALYA'),
       (9, 1, 'ARDAHAN'),
       (10, 1, 'ARTVİN'),
       (11, 1, 'AYDIN'),
       (12, 1, 'BALIKESİR'),
       (13, 1, 'BARTIN'),
       (14, 1, 'BATMAN'),
       (15, 1, 'BAYBURT'),
       (16, 1, 'BİLECİK'),
       (17, 1, 'BİNGÖL'),
       (18, 1, 'BİTLİS'),
       (19, 1, 'BOLU'),
       (20, 1, 'BURDUR'),
       (21, 1, 'BURSA'),
       (22, 1, 'ÇANAKKALE'),
       (23, 1, 'ÇANKIRI'),
       (24, 1, 'ÇORUM'),
       (25, 1, 'DENİZLİ'),
       (26, 1, 'DİYARBAKIR'),
       (27, 1, 'DÜZCE'),
       (28, 1, 'EDİRNE'),
       (29, 1, 'ELAZIĞ'),
       (30, 1, 'ERZİNCAN'),
       (31, 1, 'ERZURUM'),
       (32, 1, 'ESKİŞEHİR'),
       (33, 1, 'GAZİANTEP'),
       (34, 1, 'GİRESUN'),
       (35, 1, 'GÜMÜŞHANE'),
       (36, 1, 'HAKKARİ'),
       (37, 1, 'HATAY'),
       (38, 1, 'IĞDIR'),
       (39, 1, 'ISPARTA'),
       (40, 1, 'İSTANBUL'),
       (41, 1, 'İZMİR'),
       (42, 1, 'KAHRAMANMARAŞ'),
       (43, 1, 'KARABÜK'),
       (44, 1, 'KARAMAN'),
       (45, 1, 'KARS'),
       (46, 1, 'KASTAMONU'),
       (47, 1, 'KAYSERİ'),
       (48, 1, 'KIRIKKALE'),
       (49, 1, 'KIRKLARELİ'),
       (50, 1, 'KIRŞEHİR'),
       (51, 1, 'KİLİS'),
       (52, 1, 'KOCAELİ'),
       (53, 1, 'KONYA'),
       (54, 1, 'KÜTAHYA'),
       (55, 1, 'MALATYA'),
       (56, 1, 'MANİSA'),
       (57, 1, 'MARDİN'),
       (58, 1, 'MERSİN'),
       (59, 1, 'MUĞLA'),
       (60, 1, 'MUŞ'),
       (61, 1, 'NEVŞEHİR'),
       (62, 1, 'NİĞDE'),
       (63, 1, 'ORDU'),
       (64, 1, 'OSMANİYE'),
       (65, 1, 'RİZE'),
       (66, 1, 'SAKARYA'),
       (67, 1, 'SAMSUN'),
       (68, 1, 'SİİRT'),
       (69, 1, 'SİNOP'),
       (70, 1, 'SİVAS'),
       (71, 1, 'ŞANLIURFA'),
       (72, 1, 'ŞIRNAK'),
       (73, 1, 'TEKİRDAĞ'),
       (74, 1, 'TOKAT'),
       (75, 1, 'TRABZON'),
       (76, 1, 'TUNCELİ'),
       (77, 1, 'UŞAK'),
       (78, 1, 'VAN'),
       (79, 1, 'YALOVA'),
       (80, 1, 'YOZGAT'),
       (81, 1, 'ZONGULDAK')
ON CONFLICT (id) DO NOTHING;

-- Manuel ID girdiğimiz için sequence'i son ID'ye "81" eşitliyoruz.
-- Bunu yapılmazsa, bir sonraki insert işleminde ID 1 vermeye çalışır ve patlar.
SELECT setval('cities_id_seq', (SELECT MAX(id) FROM cities));
SELECT setval('countries_id_seq', (SELECT MAX(id) FROM countries));